version: "3.9"
services:
  web:
    build: .
    container_name: forecast_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    restart: unless-stopped
    command: gunicorn app:app -b 0.0.0.0:8000 --workers 2 --threads 4
volumes:
  data:
    driver: local

